src/main/java/shop/tryit/TryitApplication.java
src/main/java/shop/tryit/domain/common/BaseTimeEntity.java

- 공통속성 클래스 개발
- domain/common 패키지에 BaseDateEntity 클래스 파일 생성
- Auditing을 통해 등록일, 수정일 공통속성으로 사용한다.

feat: 공통속성 클래스 개발

---

src/main/java/shop/tryit/repository/member/MemberJpaRepository.java
src/main/java/shop/tryit/repository/member/MemberRepositoryImpl.java
src/test/java/shop/tryit/repository/member/MemberRepositoryImplTests.java

- 회원 레포지토리 패키지명 변경
- Repository -> repository 로 패키지명 변경

refactor: 회원 레포지토리 패키지명 변경

---

src/main/java/shop/tryit/domain/item/Category.java
src/main/java/shop/tryit/domain/item/Item.java
src/main/java/shop/tryit/domain/item/ItemImage.java

- 상품 관련 엔티티 생성
- 상품 엔티티 : Item
- 상품 이미지 엔티티 : ItemImage
- 샹품 카테고리 엔티티 : Category

feat: 상품 관련 엔티티 생성

---

src/main/java/shop/tryit/domain/answer/Answer.java
src/main/java/shop/tryit/domain/question/Question.java

- QnA 게시판 엔티티 생성
- 질문 게시판 엔티티 생성
- 답변 엔티티 생성

feat: QnA 게시판 엔티티 생성

---

src/main/java/shop/tryit/domain/item/Item.java
src/main/java/shop/tryit/domain/item/ItemImage.java

- 상품 관련 엔티티 연관관계 수정
- Item -> Category 엔티티간 연관관계 수정
- Item <-> ItemImage 엔티티간 연관관계 매핑 추가
- 영속성 전이 추가 (cascade = PERSIST, REMOVE)
- 필드 컬렉션 초기화

refector: 상품 관련 엔티티 연관관계 수정

---

src/main/java/shop/tryit/domain/answer/Answer.java
src/main/java/shop/tryit/domain/question/Question.java
src/main/java/shop/tryit/domain/question/QuestionRepository.java
src/main/java/shop/tryit/domain/question/QuestionService.java
src/main/java/shop/tryit/repository/question/QuestionJpaRepository.java
src/main/java/shop/tryit/repository/question/QuestionRepositoryImpl.java
src/test/java/shop/tryit/domain/question/QuestionServiceTests.java
src/test/java/shop/tryit/repository/question/QuestionRepositoryImplTests.java

- 질문 엔티티 저장 기능 구현
- 질문 엔티티 저장 기능 구현

feat: 질문 엔티티 저장 기능 구현

---

build.gradle
src/main/java/shop/tryit/WebSecurityConfig.java
src/main/java/shop/tryit/domain/member/Member.java
src/main/java/shop/tryit/domain/member/MemberFormDto.java
src/main/java/shop/tryit/domain/member/MemberService.java
src/test/java/shop/tryit/PasswordEncoderTest.java
src/test/java/shop/tryit/domain/member/MemberServiceTests.java

- Security 설정 및 회원 서비스 생성
- 초기 Security 설정 
- 회원 서비스 구현
- 회원 서비스 테스트 완료(회원 가입, 중복 회원)

Feat: 초기 Spring Security 설정 및 회원 서비스 생성

---

src/main/java/shop/tryit/domain/item/ItemRepository.java
src/main/java/shop/tryit/repository/item/ItemJpaRepository.java
src/main/java/shop/tryit/repository/item/ItemRepositoryImpl.java
src/test/java/shop/tryit/domain/item/ItemRepositoryTests.java

- 상품 레포 생성과 테스트 진행
- 상품 레포지토리 인터페이스 생성
- 상품 레포지토리 구현체 생성
- 테스트 진행(상품 저장, 상품 한개 조회, 상품 전체 조회)

feat: 상품 레포지토리 생성 및 테스트

---

src/main/java/shop/tryit/domain/question/QuestionRepository.java
src/main/java/shop/tryit/domain/question/QuestionService.java
src/main/java/shop/tryit/repository/question/QuestionRepositoryImpl.java

- 게시판 조회 기능 구현
- 게시판 조회 기능 구현 (리포지토리)
- 게시판 조회 기능 구현 (서비스)

feat: 게시판 조회 기능 구현

---

src/main/java/shop/tryit/domain/answer/Answer.java
src/main/java/shop/tryit/domain/answer/AnswerRepository.java
src/main/java/shop/tryit/domain/answer/AnswerService.java
src/main/java/shop/tryit/repository/answer/AnswerJpaRepository.java
src/main/java/shop/tryit/repository/answer/AnswerRepositoryImpl.java
src/test/java/shop/tryit/domain/answer/AnswerServiceTests.java

-답변 저장 기능 구현
- 답변 저장 기능 구현 (리포지토리)
- 답변 저장 기능 구현 (서비스)

feat: 답변 저장 기능 구현

---

src/main/java/shop/tryit/domain/question/QuestionService.java
src/test/java/shop/tryit/domain/question/QuestionServiceTests.java

- 게시판 수정 기능 구현
- 게시판 수정 기능 구현
- 게시판 수정 기능 테스트 구현

게시판 수정 기능 구현

---

src/main/java/shop/tryit/WebSecurityConfig.java
src/main/resources/static/css/style.css
src/main/resources/templates/fragments/bodyHeader.html
src/main/resources/templates/fragments/header.html

- 시큐리티 권한 추가 및 헤더 타임리프,css 적용
- 시큐리티 권한 추가
- 헤더 타임리프 적용
- style.css 추가/삭제

refactor: 시큐리티 권한 추가 및 헤더 타임리프,css 적용

---

src/main/java/shop/tryit/domain/answer/AnswerRepository.java
src/main/java/shop/tryit/domain/answer/AnswerService.java
src/main/java/shop/tryit/repository/answer/AnswerRepositoryImpl.java
src/test/java/shop/tryit/domain/answer/AnswerServiceTests.java

- 답변 수정 기능 구현
- 답변 조회 기능 구현
- 답변 수정 기능 구현

feat : 답변 수정 기능 구현

---

src/main/java/shop/tryit/domain/answer/AnswerRepository.java
src/main/java/shop/tryit/domain/question/QuestionRepository.java
src/main/java/shop/tryit/domain/question/QuestionService.java
src/main/java/shop/tryit/repository/answer/AnswerJpaRepository.java
src/main/java/shop/tryit/repository/answer/AnswerRepositoryImpl.java
src/main/java/shop/tryit/repository/question/QuestionRepositoryImpl.java
src/test/java/shop/tryit/domain/question/QuestionServiceTests.java

-게시판 삭제 기능 구현
- 게시판 삭제 기능 구현
- 게시판에 달려있는 답글들 조회 기능 구현

feat: 게시판 삭제 기능 구현

---

src/main/java/shop/tryit/web/item/ItemController.java
src/main/java/shop/tryit/web/item/ItemFormDto.java
src/main/resources/templates/items/register.html

- 상품 등록 관련 웹 계층 개발
- 상품 등록 DTO 생성 (ItemFormDto)
- 상품 등록 폼 생성 (members/register.html)
- 상품 등록 컨트롤러 생성

feat: 상품 등록 웹 계층 개발

---

src/main/java/shop/tryit/web/member/MemberFormDto.java
src/main/resources/templates/members/register.html

- 회원 등록 DTO 어노테이션 적용 및 회원 UI 오류메세지 추가
- 회원 등록 DTO에서 주석으로 처리된 어노테이션을 다시 적용
- 회원 register.html에서 적용된 어노테이션에 따라 오류메세지를 출력할 수 있는 부분 추가

refactor: 회원 등록 DTO 어노테이션 적용

---

src/main/java/shop/tryit/domain/item/ItemFileStore.java
src/main/resources/application.yml

- 상품 파일 업로드 경로 변경
- yml에 등록된 기존 경로 제거
- 파일 업로드 경로를 프로젝트 내부가 아닌 외부(사용자 홈/item)에 두도록 수정
- @Value 빈 주입 문제로 filePath를 직접 넣어주는 방식으로 변경 ➡ 추후 리팩토링 고려

refactor: 파일 업로드 경로 관련 수정

---

src/main/java/shop/tryit/WebSecurityConfig.java
src/main/java/shop/tryit/domain/member/MemberRepository.java
src/main/java/shop/tryit/domain/member/MemberRole.java
src/main/java/shop/tryit/domain/member/MemberSecurityService.java
src/main/java/shop/tryit/repository/member/MemberJpaRepository.java
src/main/java/shop/tryit/repository/member/MemberRepositoryImpl.java
src/main/java/shop/tryit/web/member/MemberAdapter.java
src/main/java/shop/tryit/web/member/MemberController.java
src/main/java/shop/tryit/web/member/MemberFormDto.java
src/main/resources/templates/fragments/body-header.html
src/main/resources/templates/members/login-form.html

- 로그인/로그아웃 기능 구현 및 시큐리티 작업
- 로그인, 로그아웃 시큐리티
- 로그인, 로그아웃 기능 구현
- 로그인 UI 구현
- 회원 권한 부여 로직 추가

feat: 로그인/로그아웃 기능 구현 및 시큐리티 작업

---

src/main/java/shop/tryit/domain/member/MemberService.java
src/test/java/shop/tryit/domain/member/MemberServiceTests.java

- 회원 이메일을 통해 회원 찾기
- 회원 서비스에 findMember 메소드 생성

refactor: 회원 이메일을 통해 회원 찾기

---

src/main/java/shop/tryit/domain/item/ItemService.java
src/test/java/shop/tryit/domain/item/ItemServiceTests.java

- 상품 목록 기능 개발 및 테스트
- 상품 목록 서비스 로직 구현
- 상품 목록 기능 테스트

feat: 상품 목록 기능 개발 및 테스트

---

src/main/resources/templates/fragments/body-header.html
src/main/resources/templates/index.html
src/main/resources/templates/items/register.html
src/main/resources/templates/members/login-form.html
src/main/resources/templates/members/register.html
src/main/resources/templates/questions/register.html

- body-header 타임리프 수정
- body-header 파일명 변경에 따른 타임리프 수정
```
th:fragment="bodyHeader" ➡ "body-header"
th:replace="fragments/bodyHeader :: bodyHeader" ➡ "fragments/body-header :: body-header"
```

refactor: body-header 타임리프 수정

---

src/main/java/shop/tryit/domain/answer/AnswerService.java
src/test/java/shop/tryit/domain/answer/AnswerServiceTests.java

- 답변 삭제 기능 구현.
- 답변 삭제 기능 구현
- 답변 삭제 기능 테스트 구현

feat: 답변 삭제 기능 구현

---

build.gradle
src/main/java/shop/tryit/config/QuerydslConfig.java
src/main/resources/application.yml

- querydsl 설정 추가
- querydsl 설정 추가
- JPAQueryFactory 빈 등록
- OSIV false 설정

feat: querydsl 설정 추가

---

src/main/java/shop/tryit/domain/member/Member.java
src/main/java/shop/tryit/domain/member/MemberService.java
src/main/java/shop/tryit/web/member/AddressAdapter.java
src/main/java/shop/tryit/web/member/MemberAdapter.java
src/main/java/shop/tryit/web/member/MemberController.java
src/main/resources/templates/members/edit.html

- 회원 정보 수정 기능 구현
- 회원 수정 컨트롤러 생성
- 회원 엔티티 update 메소드 생성
- 회원 서비스 update 메소드 생성
- 회원 어댑터에서 회원 수정에서만 변하는 dto를 Entity로 변환해주는 메소드 추가
- 회원 어댑터에서 toEntity 부분에 회원 주소 파트 수정

feat: 회원 정보 수정 기능 구현

---

src/main/java/shop/tryit/domain/item/ItemFileService.java
src/main/java/shop/tryit/domain/item/ItemFileStore.java
src/main/java/shop/tryit/web/item/ItemAdapter.java
src/main/java/shop/tryit/web/item/ItemController.java
src/main/java/shop/tryit/web/item/ItemFileController.java
src/main/java/shop/tryit/web/item/ItemListDto.java
src/main/resources/templates/items/list.html

- 상품 목록 웹 계층(컨트롤러, 뷰) 개발
- 상품 목록 DTO 생성
- 상품 목록 엔티티를 상품 목록 DTO로 변환해주는 어댑터 기능 추가
- 상품 파일 서비스 생성
- 상품 목록 컨트롤러 구현
- 상품 목록 뷰(list.html) 생성
- 상품 이미지 엑박 문제 해결을 위한 상품 이미지 파일 컨트롤러 생성

feat: 상품 목록 웹 계층 개발

---

src/main/java/shop/tryit/domain/question/QuestionRepository.java
src/main/java/shop/tryit/domain/question/QuestionSearchCondition.java
src/main/java/shop/tryit/domain/question/QuestionSearchDto.java
src/main/java/shop/tryit/repository/question/QuestionCustom.java
src/main/java/shop/tryit/repository/question/QuestionCustomImpl.java
src/main/java/shop/tryit/repository/question/QuestionJpaRepository.java
src/main/java/shop/tryit/repository/question/QuestionRepositoryImpl.java
src/test/java/shop/tryit/repository/question/QuestionRepositoryImplTests.java
src/test/resources/application.yml

- 질문 리포지토리의 페이징 기능 구현
- 질문 리포지토리의 페이징 기능 구현
- test yml에 쿼리 로그 보이도록 설정

feat: 질문 리포지토리의 페이징 기능 구현

---

src/main/java/shop/tryit/domain/item/Image.java
src/main/java/shop/tryit/domain/item/ImageService.java
src/main/java/shop/tryit/domain/item/ImageStore.java
src/main/java/shop/tryit/domain/item/ImageType.java
src/main/java/shop/tryit/domain/item/Item.java
src/main/java/shop/tryit/web/item/ItemAdapter.java
src/main/java/shop/tryit/web/item/ItemController.java
src/main/java/shop/tryit/web/item/ItemFileController.java
src/main/java/shop/tryit/web/item/ItemListDto.java

- 상품 이미지 파일 관련 리팩토링 
- 상품 이미지 관련 파일명 변경 (이름이 헷갈려서 수정합니다)
- ItemFile ➡ Image
- ItemFileType ➡ ImageType
- ItemFileStore ➡ ImageStore
- ItemFileService ➡ ImageService
- 컨트롤러에 있는 이미지 파일 업로드 로직을 서비스로 분리
- Item 엔티티 빌더 생성자에 images 파라미터를 제거하고 addImage 매소드로 해결

refactor: 상품 이미지 파일 관련 리팩토링

---

src/main/java/shop/tryit/domain/question/QuestionSearchCondition.java
src/main/java/shop/tryit/domain/question/QuestionSearchDto.java
src/main/java/shop/tryit/domain/question/QuestionService.java
src/main/java/shop/tryit/repository/question/QuestionCustomImpl.java
src/main/java/shop/tryit/web/question/QuestionController.java
src/main/resources/templates/questions/list.html
src/test/java/shop/tryit/domain/question/QuestionServiceTests.java

- 질문 검색 기능 페이징 컨트롤 구현
- 질문 검색 기능 페이징 컨트롤 구현
- 질문 리스트 html 구현
- 질문 등록시 회원 정보 조회 기능 추가

feat: 질문 검색 기능 페이징 컨트롤 구현

---

src/main/java/shop/tryit/web/member/MemberFormDto.java
src/main/resources/templates/fragments/body-header.html
src/main/resources/templates/members/register.html

-  회원가입 검증 애노테이션 추가 및 네비게이션 경로 수정
- MemberFormDto 에서 비밀번호, 전화번호 부분에 @Pattern 애노테이션 추가
- 회원 가입 View에서 전화번호 오류 메시지가 보이도록 타임리프 th:errors 추가
- 네이게이션 경로를 도메인에 맞게 수정 및 로그인 권한에 따라 네이게이션의 버튼 표출 수정

refactor:  회원가입 검증 애노테이션 추가 및 네비게이션 경로 수정

---

src/main/java/shop/tryit/domain/member/InitDB.java
src/main/java/shop/tryit/domain/member/MemberRole.java
src/main/java/shop/tryit/domain/member/MemberSecurityService.java
src/main/java/shop/tryit/domain/member/MemberService.java
src/main/java/shop/tryit/web/member/MemberController.java

- 회원 관련 리팩토링
- 회원 수정 시 비밀번호 암호화가 되지 않는 이슈를 발견하여 service 클래스에 비밀번호 암호화 로직 추가
- 회원 권한 Enum을 설정할 때 "ROLE_"이 있는 것이 컨벤션이라 하여 변수명 변경
- 회원 권한에 따른 테스트를 진행하기 위해 각각 다른 권한을 가지고 있는 회원 샘플 데이터 클래스를 생성

refactor: 회원 관련 리팩토링

---

src/main/java/shop/tryit/domain/item/ImageService.java
src/main/java/shop/tryit/domain/item/ImageStore.java
src/main/java/shop/tryit/web/item/ImageController.java
src/main/java/shop/tryit/web/item/ItemAdapter.java
src/main/java/shop/tryit/web/item/ItemController.java

- 상품 관련 리팩토링
- 메소드명 변경 : `storeItemFile` -> `storeImageFile`
- 클래스명 변경 : `ItemFileController` -> `ImageController`
- 상품 엔티티에 이미지 파일을 추가하는 로직을 어댑터가 아닌 컨트롤러에서 처리하도록 수정
- 로그 수정

refactor: 상품 관련 리팩토링

---

src/main/java/shop/tryit/domain/common/OrderStatus.java
src/main/java/shop/tryit/domain/member/Member.java
src/main/java/shop/tryit/domain/order/Order.java
src/main/java/shop/tryit/domain/order/OrderDetail.java
src/main/java/shop/tryit/domain/order/OrderStatus.java

- 주소 관련 엔티티 클래스 생성
- Order 엔티티 생성
- OrderStatus Enum 생성
- OrderDetail 엔티티 생성
- Member 엔티티에 Order엔티티 연관 관계 추가

feat: 주소 관련 엔티티 클래스 생성

---

src/main/java/shop/tryit/domain/item/ImageStore.java
src/main/java/shop/tryit/web/item/ItemController.java
src/main/java/shop/tryit/web/item/ItemDto.java
src/main/java/shop/tryit/web/item/ItemFormDto.java
src/main/resources/static/css/style.css
src/main/resources/templates/items/register.html
src/main/resources/templates/items/update.html

- 상품 관련 검증 사항을 적용
- Bean Validation 어노테이션을 사용
- 상품 등록 검증 사항 적용  
- 상품 수정 검증 사항 적용
- 검증 오류 메세지에 대한 css 추가  
- 상품 등록 시 이미지 파일이 없을 검증 오류가 일어나도록 rejectValue를 사용해 추가

feat: 상품 검증 사항 적용

---

src/main/java/shop/tryit/web/answer/AnswerAdapter.java
src/main/java/shop/tryit/web/answer/AnswerController.java
src/main/java/shop/tryit/web/answer/AnswerFormDto.java

- 답변 등록 기능 구현
- 답변 등록 기능 구현
- 답변 어댑터 구현
- 답변 등록 폼 구현

feat: 답변 등록 기능 구현

---

src/main/resources/static/css/style.css
src/main/resources/templates/fragments/body-header.html
src/main/resources/templates/fragments/footer.html
src/main/resources/templates/fragments/header.html

- 전반적인 font css 변경
- html, css 코드 정렬
- 전체 폰트 변경 (이서윤체, Open Sans)
- 필요 없는 `font-family` 지정 css 삭제
- 푸터 이름 글씨를 `h3` -> `h4` 태그로 변경

refactor:  font css 변경

---

src/main/java/shop/tryit/domain/order/Order.java
src/main/java/shop/tryit/domain/order/OrderDetail.java
src/main/java/shop/tryit/domain/order/OrderDetailRepository.java
src/main/java/shop/tryit/domain/order/OrderRepository.java
src/main/java/shop/tryit/repository/order/OrderDetailJpaRepository.java
src/main/java/shop/tryit/repository/order/OrderDetailRepositoryImpl.java
src/main/java/shop/tryit/repository/order/OrderJpaRepository.java
src/main/java/shop/tryit/repository/order/OrderRepositoryImpl.java

- 주문 관련 레파지토리 생성 및 주문 관련 엔티티 리팩토링
- 주문 관련 레파지토리 생성
- 주문 관련 엔티티 리팩토링

feat: 주문 관련 레파지토리 생성 및 주문 관련 엔티티 리팩토링

---

src/main/java/shop/tryit/domain/answer/AnswerRepository.java
src/main/java/shop/tryit/domain/answer/AnswerService.java
src/main/java/shop/tryit/repository/answer/AnswerJpaRepository.java
src/main/java/shop/tryit/repository/answer/AnswerRepositoryImpl.java
src/main/java/shop/tryit/web/answer/AnswerAdapter.java
src/main/java/shop/tryit/web/answer/AnswerController.java
src/main/java/shop/tryit/web/answer/AnswerFormDto.java
src/main/java/shop/tryit/web/question/QuestionAdapter.java
src/main/java/shop/tryit/web/question/QuestionController.java
src/main/java/shop/tryit/web/question/QuestionFormDto.java
src/main/resources/templates/questions/detail-view.html
src/test/java/shop/tryit/domain/answer/AnswerServiceTests.java

- 게시판 세부 조회 기능 구현
- 게시판 세부 조회 기능 구현
- 댓글 등록 기능 구현

feat: 게시판 세부 조회 기능 구현

---

src/main/java/shop/tryit/domain/item/ImageService.java
src/main/java/shop/tryit/domain/item/ItemRepository.java
src/main/java/shop/tryit/domain/item/ItemService.java
src/main/java/shop/tryit/repository/item/ItemRepositoryImpl.java
src/main/java/shop/tryit/web/item/ItemController.java
src/main/resources/static/css/style.css
src/main/resources/templates/items/detail.html
src/test/java/shop/tryit/domain/item/ItemServiceTests.java

- 상품 삭제 기능 개발
- 상품 삭제 레포지토리, 서비스 로직 구현
- 상품 삭제 서비스 `test` 진행
- 상품 이미지 삭제 서비스 로직 구현
- 상품 상세 페이지에 상품 삭제 버튼 추가
- 상품 삭제 컨트롤러 구현
- 코드 정렬

feat: 상품 삭제 기능 개발

---

build.gradle

- spring dev tools 의존성 관계 추가
- spring dev tools 의존성 관계 추가
``` java
implementation 'org.springframework.boot:spring-boot-devtools:2.7.1'
```

build: spring dev tools 의존성 관계 추가

---

src/main/java/shop/tryit/domain/common/Pages.java
src/main/java/shop/tryit/web/question/QuestionController.java
src/main/resources/templates/questions/detail-view.html
src/main/resources/templates/questions/list.html

- 페이징 번호 구하는 페이지 클래스 구현
- 뷰에서 보여주기 위한 페이징 번호를 구할 때 컨트롤러에서 하는 것보다 Pages 클래스를 만들어 Pages 클래스에게 기능을 위임했습니다.

feat: 페이징 번호 구하는 페이지 클래스 구현

---

src/main/java/shop/tryit/web/question/QuestionAdapter.java
src/main/java/shop/tryit/web/question/QuestionController.java
src/main/java/shop/tryit/web/question/QuestionFormDto.java
src/main/resources/templates/questions/detail-view.html
src/main/resources/templates/questions/update.html

- 게시판 수정 기능 구현
- 게시판 수정 기능 구현
- 게시판 세부 조회 뷰에 수정하기 버튼 추가
- 게시판 수정 폼 구현

feat: 게시판 수정 기능 구현

---

src/main/java/shop/tryit/domain/answer/Answer.java
src/main/java/shop/tryit/domain/answer/AnswerService.java
src/main/java/shop/tryit/web/answer/AnswerController.java
src/main/resources/templates/questions/detail-view.html

feat: 댓글 삭제 처리 구현

---

src/main/java/shop/tryit/domain/item/Item.java

- 상품 재고 update 이슈 해결
- 상품 엔티티에 재고 수정 비즈니스 로직에 stockQuantity가 price로 설정되는 부분 수정
`this.stockQuantity = stockQuantity;`

refactor: 상품 재고 update 이슈 해결

---

src/main/java/shop/tryit/domain/question/Question.java
src/main/java/shop/tryit/domain/question/QuestionService.java
src/main/java/shop/tryit/web/question/QuestionCheckPasswordFormDto.java
src/main/java/shop/tryit/web/question/QuestionController.java
src/main/java/shop/tryit/web/question/QuestionSaveFormDto.java
src/main/resources/templates/questions/check-password.html
src/main/resources/templates/questions/detail-view.html
src/main/resources/templates/questions/register.html

- 질문 게시판에 비밀번호 암호 기능 구현
- 질문 게시판에 비밀번호 암호 기능 구현

feat: 질문 게시판에 비밀번호 암호 기능 구현

---

src/main/java/shop/tryit/domain/notice/Notice.java
src/main/java/shop/tryit/domain/notice/NoticeRepository.java
src/main/java/shop/tryit/repository/notice/NoticeJpaRepository.java
src/main/java/shop/tryit/repository/notice/NoticeRepositoryImpl.java

-  공지 게시판 엔티티 구현
-  공지 엔티티 구현
- 공지 리포지토리 구현
- 공지 리포지토리의 기본 CRUD 구현

feat: 공지 게시판 엔티티 구현

---

src/main/java/shop/tryit/domain/notice/NoticeService.java
src/test/java/shop/tryit/domain/notice/NoticeServiceTests.java

- 공지 서비스의 CRUD 기능 구현
- 공지 서비스의 CRUD 기능 구현

feat: 공지 서비스의 CRUD 기능 구현

---

src/main/java/shop/tryit/web/notice/NoticeAdapter.java
src/main/java/shop/tryit/web/notice/NoticeController.java
src/main/java/shop/tryit/web/notice/NoticeSaveFormDto.java
src/main/java/shop/tryit/web/notice/NoticeViewFormDto.java
src/main/resources/templates/notices/detail.html
src/main/resources/templates/notices/register.html

- 공지 컨트롤러의 등록 및 단건 조회 기능 구현 
- 공지 컨트롤러의 등록 기능 구현
- 공지 컨트롤러의 단건 조회 기능 구현

feat: 공지 컨트롤러의 등록 및 단건 조회 기능 구현 

---

src/main/java/shop/tryit/web/notice/NoticeAdapter.java
src/main/java/shop/tryit/web/notice/NoticeController.java
src/main/java/shop/tryit/web/notice/NoticeUpdateFormDto.java
src/main/resources/templates/notices/update.html

feat: 공지 컨트롤러의 수정 기능 구현

---

src/main/java/shop/tryit/web/notice/NoticeController.java
src/main/resources/templates/notices/detail.html

feat: 공지 컨트롤러의 삭제 기능 구현

---

src/main/java/shop/tryit/repository/item/ItemCustomImpl.java

- `QItemSearchDto`를 web 계층에서 domain 계층으로 이동

refactor: QItemSearchDto를 domain 계층으로 이동

---

src/main/java/shop/tryit/domain/order/OrderDetail.java
src/main/java/shop/tryit/domain/order/OrderDetailRepository.java
src/main/java/shop/tryit/domain/order/OrderRepository.java
src/main/java/shop/tryit/domain/order/OrderService.java
src/main/java/shop/tryit/repository/order/OrderDetailRepositoryImpl.java
src/main/java/shop/tryit/repository/order/OrderJpaRepository.java
src/main/java/shop/tryit/repository/order/OrderRepositoryImpl.java
src/main/java/shop/tryit/web/order/OrderAdapter.java
src/main/java/shop/tryit/web/order/OrderController.java
src/main/java/shop/tryit/web/order/OrderDto.java
src/main/java/shop/tryit/web/order/OrderFormDto.java
src/main/resources/templates/fragments/body-header.html
src/main/resources/templates/orders/list.html
src/test/java/shop/tryit/domain/order/OrderServiceTests.java

- 단건 주문 관련 웹 계층 구현
- 단건 주문 후 주문 목록 표출을 위한 서비스 로직 추가
- 주문 관련 컨트롤러 생성
- 주문 관련 어댑터 생성
- 주문 관련 레포지토리 리팩토링

feat: 단건 주문 관련 웹 계층 구현

---

src/main/java/shop/tryit/domain/notice/NoticeRepository.java
src/main/java/shop/tryit/domain/notice/NoticeService.java
src/main/java/shop/tryit/repository/notice/NoticeRepositoryImpl.java
src/main/java/shop/tryit/web/notice/NoticeAdapter.java
src/main/java/shop/tryit/web/notice/NoticeController.java
src/main/java/shop/tryit/web/notice/NoticeSearchFormDto.java
src/main/resources/templates/notices/list.html

feat: 공지 목록 보기 기능 구현

---

src/main/java/shop/tryit/domain/cart/repository/CartItemRepository.java
src/main/java/shop/tryit/domain/cart/repository/CartRepository.java
src/main/java/shop/tryit/domain/cart/service/CartItemService.java
src/main/java/shop/tryit/domain/cart/service/CartService.java
src/main/java/shop/tryit/repository/cart/CartItemJpaRepository.java
src/main/java/shop/tryit/repository/cart/CartItemRepositoryImpl.java
src/main/java/shop/tryit/repository/cart/CartJpaRepository.java
src/main/java/shop/tryit/repository/cart/CartRepositoryImpl.java
src/test/java/shop/tryit/domain/cart/CartItemServiceTests.java
src/test/java/shop/tryit/domain/cart/CartServiceTests.java

- 장바구니 관련 레포지토리, 서비스 개발 (등록 기능) 
- 장바구니 레포지토리 인터페이스와 구현체 개발
- 저장 기능 : `save()` 
- 장바구니 상품 레포지토리 인터페이스와 구현체 개발   
- 저장 기능 : `save()`
- 장바구니 등록 비즈니스 로직 개발 및 테스트 진행
- 등록 기능 : `register()`
- 장바구니 상품 등록 비즈니스 로직 개발 및 테스트 진행
- 등록 기능 : `register()`

feat: 장바구니 관련 등록 기능 개발 

---

src/main/java/shop/tryit/domain/payment/Payment.java
src/main/java/shop/tryit/domain/payment/PaymentRepository.java
src/main/java/shop/tryit/domain/payment/PaymentService.java
src/main/java/shop/tryit/repository/payment/PaymentJpaRepository.java
src/main/java/shop/tryit/repository/payment/PaymentRepositoryImpl.java
src/test/java/shop/tryit/domain/payment/PaymentServiceTests.java

- 결제 정보 저장을 위해 엔티티, 레포지토리, 서비스 로직을 생성하였습니다.
- 결제 엔티티 생성
- 결제 레포지토리 생성
- 결제 정보 저장 서비스 로직 생성 및 테스트

feat: 결제 정보 저장 기능 구현

---

src/main/java/shop/tryit/domain/cart/repository/CartItemRepository.java
src/main/java/shop/tryit/domain/cart/service/CartItemService.java
src/main/java/shop/tryit/repository/cart/CartItemJpaRepository.java
src/main/java/shop/tryit/repository/cart/CartItemRepositoryImpl.java
src/test/java/shop/tryit/domain/cart/CartItemServiceTests.java

- 장바구니에 담긴 상품을 조회하는 기능을 개발
- 장바구니 상품 레포지토리에 `findByCart()` 추가
- 장바구니에 담긴 상품을 조회하는 비즈니스 로직 구현 : `findCartItemList()`
- 장바구니에 담긴 상품을 조회하는 비즈니스 로직 테스트 코드 구현

feat: 장바구니 조회 서비스 로직 개발

---

src/main/java/shop/tryit/domain/order/Order.java
src/main/java/shop/tryit/domain/order/OrderDetail.java

- 주문, 주문상품 엔티티에 equals, hashcode 오버라이딩
- pk값인 id 값을 기반으로 equals, hashcode 오버라이딩

feat: 주문, 주문상품 엔티티에 equals, hashcode 오버라이딩

---

src/main/java/shop/tryit/domain/item/ItemRepository.java
src/main/java/shop/tryit/repository/item/ItemCustom.java
src/main/java/shop/tryit/repository/item/ItemCustomImpl.java
src/main/java/shop/tryit/repository/item/ItemRepositoryImpl.java
src/test/java/shop/tryit/domain/item/ItemRepositoryTests.java

- 상품 리포지토리에서 주문 상품 조회
- 상품 리포지토리에서 주문 상품 조회
- 상품 리포지토리에서 주문 상품 조회 테스트 구현

feat: 상품 리포지토리에서 주문 상품 조회

---

src/main/java/shop/tryit/domain/order/OrderDetail.java
src/main/java/shop/tryit/domain/order/OrderDetailRepository.java
src/main/java/shop/tryit/domain/order/OrderDetailSearchDto.java
src/main/java/shop/tryit/domain/order/OrderSearchDto.java
src/main/java/shop/tryit/repository/order/OrderDetailCustom.java
src/main/java/shop/tryit/repository/order/OrderDetailCustomImpl.java
src/main/java/shop/tryit/repository/order/OrderDetailJpaRepository.java
src/main/java/shop/tryit/repository/order/OrderDetailRepositoryImpl.java

- 주문 기준으로 주문 상품 조회 기능 구현
- 주문 수량 변수명 수정
- 주문 상품 조회 기능 구현

feat: 주문 기준으로 주문 상세 조회 기능 구현

---

src/main/java/shop/tryit/repository/order/OrderCustom.java
src/main/java/shop/tryit/repository/order/OrderCustomImpl.java
src/main/java/shop/tryit/repository/order/OrderJpaRepository.java
src/main/java/shop/tryit/repository/order/OrderRepositoryImpl.java
src/main/java/shop/tryit/web/order/OrderAdapter.java
src/test/java/shop/tryit/domain/item/ItemRepositoryTests.java
src/test/java/shop/tryit/domain/order/OrderServiceTests.java

feat: 주문 레포지토리에서 주문 페이징 기능 구현

---

src/main/java/shop/tryit/web/order/OrderController.java

- OrderAdapter의 엔티티 변환 파라미터 수정

refactor: 주문 어댑터의 엔티티 변환 파라미터 수정

---

src/main/java/shop/tryit/domain/order/OrderSearchDto.java
src/main/java/shop/tryit/repository/order/OrderCustomImpl.java

refactor: 주문 dto에 주소지 추가

---

src/main/java/shop/tryit/domain/member/Member.java
src/main/java/shop/tryit/domain/payment/Payment.java
src/main/java/shop/tryit/domain/payment/PaymentRepository.java
src/main/java/shop/tryit/repository/payment/PaymentJpaRepository.java
src/main/java/shop/tryit/repository/payment/PaymentRepositoryImpl.java
src/main/java/shop/tryit/web/payment/PaymentAdapter.java
src/main/java/shop/tryit/web/payment/PaymentController.java
src/main/java/shop/tryit/web/payment/PaymentDto.java
src/main/java/shop/tryit/web/payment/PaymentRequsetDto.java
src/main/java/shop/tryit/web/payment/PaymentResponseDto.java
src/main/resources/templates/payment/payment-form.html

- 단건 주문 관련하여 결제 처리 기능을 추가 수정하였습니다.
- PaymentResponseDto 생성
- 상품상세에서 주문하기 버튼 클릭 시 넘어오는 데이터를 사용하여 결제 폼에 표출 및 결제 진행 후 주문 컨트롤러로 결제 후 데이터를 보내는 부분까지 추가 수정하였습니다.
@kureung 
- 주문 컨트롤러에서 로그로 값이 잘 넘어오는 지만 확인하였기 때문에 주문 관련 저장이 잘 되는지 확인해주시면 될 것 같아요‼

refactor: 결제 웹 계층 리팩토링(단건 주문결제)

---

src/main/java/shop/tryit/domain/order/OrderService.java
src/main/java/shop/tryit/repository/order/OrderCustomImpl.java
src/main/java/shop/tryit/web/order/OrderController.java
src/main/resources/templates/orders/list.html

feat: 주문 페이징 기능 구현

---

src/main/resources/templates/payment/payment-form.html

- 주문 폼에서 주문 컨트롤러로 데이터 전달 js 로직 구현
- 주문 폼에서 결제 완료 후 주문 컨트롤러로 JSON 데이터를 보내주는 js 로직을 구현

feat: 주문 폼에서 주문 컨트롤러로 데이터 전달 js 로직 구현

---

src/test/java/shop/tryit/domain/payment/PaymentServiceTests.java

- Payment 엔티티에 있는 Number 의 자료형 변경으로 생긴 오류 수정
- String -> Long 타입으로 파라미터 타입 변경

refactor: 결제 서비스 테스트 수정

---

src/main/java/shop/tryit/repository/item/ItemCustomImpl.java

- 상품 도메인 패키지 변경에 따른 Q객체 변경 내용이 빠져서 추가합니다.

refactor: 상품 도메인 계층 패키지 변경 추가

---

src/main/java/shop/tryit/domain/cart/service/CartFacade.java

- 엔티티 조회 시 프록시 이슈 해결을 위해 메소드에 `@Transactional(readOlny=ture)`를 추가

refactor: CartFacade에 @Transactional 추가

---

src/main/java/shop/tryit/domain/order/service/OrderFacade.java
src/main/java/shop/tryit/domain/question/service/QnAFacade.java
src/main/java/shop/tryit/repository/order/OrderCustomImpl.java
src/main/java/shop/tryit/repository/question/QuestionCustomImpl.java

- 퍼사드 패턴에 트랜잭션 어노테이션 추가
- 퍼사드 패턴에 트랜잭션 어노테이션 추가
- Q파일 패키지 변경

refactor: OrderFacade, QnaFacade에 @Transactional 추가

---

src/main/java/shop/tryit/domain/answer/service/AnswerService.java
src/main/java/shop/tryit/domain/question/service/QnAFacade.java
src/main/java/shop/tryit/domain/question/service/QuestionService.java

- 트랜잭션을 QnA 서비스가 아닌 퍼사드에 적용
- QnA 서비스에 트랜잭션 제거
- QnA 퍼사드에 트랜잭션 추가

refactor: 트랜잭션을 QnA 서비스가 아닌 퍼사드에 적용

---

src/main/java/shop/tryit/domain/order/OrderDetail.java
src/main/java/shop/tryit/domain/order/service/OrderDetailService.java

refactor: 주문 상세 등록시 상품 재고 감소 기능 추가

---

src/main/resources/static/css/cart.css
src/main/resources/templates/cart/list.html

- 장바구니 목록에서 checkbox 처리 및 주문 상품 데이터 전달
- 장바구니 checkbox 기능 구현
- 체크박스 전체 선택
- 체크박스 체크 유무에 따라 총 장바구니 정보 변경
- 주문하기 버튼 클릭시, 체크된 장바구니 상품 리스트 데이터를 결제 컨트롤러로 전달

feat: 장바구니 목록에서 checkbox 처리 및 주문 상품 데이터 전달

---

src/main/java/shop/tryit/domain/order/service/OrderFacade.java
src/main/java/shop/tryit/domain/order/service/OrderService.java

refactor: 주문 목록 기능의 파라미터 수정

---

src/main/resources/templates/items/detail.html

refactor: 상품 상세 폼에서 input name 태그 수정

---

src/main/java/shop/tryit/web/cart/CartController.java

- 장바구니 상품 담기 컨트롤러에서 반환하는 응답코드를 200에서 201로 변경

refactor: 장바구니 상품 담기 컨트롤러에서 반환하는 성공 응답코드 변경

---

src/main/java/shop/tryit/domain/cart/service/CartFacade.java
src/main/java/shop/tryit/domain/item/entity/Item.java
src/main/java/shop/tryit/web/cart/CartController.java
src/main/resources/templates/carts/list.html

- 장바구니에서 수량 변경이 이뤄질 경우, 상품의 재고보다 많은 수량을 선택할 수 없도록 검증 사항을 추가

feat: 장바구니에서 수량 변경 시 충분한 재고가 있는지 검증 사항 추가

---

src/main/java/shop/tryit/domain/item/repository/ItemRepository.java
src/main/java/shop/tryit/domain/order/dto/OrderDetailSearchDto.java
src/main/java/shop/tryit/repository/item/ItemCustom.java
src/main/java/shop/tryit/repository/item/ItemCustomImpl.java
src/main/java/shop/tryit/repository/item/ItemRepositoryImpl.java
src/main/java/shop/tryit/repository/order/OrderCustomImpl.java
src/main/java/shop/tryit/repository/order/OrderDetailCustomImpl.java
src/test/java/shop/tryit/domain/item/ItemRepositoryTests.java

refactor: 주문 상세 dto 조회 기능 수정

---

src/main/java/shop/tryit/domain/item/entity/Item.java
src/main/java/shop/tryit/domain/order/Order.java
src/main/java/shop/tryit/domain/order/OrderDetail.java
src/main/java/shop/tryit/domain/order/dto/OrderFindDto.java
src/main/java/shop/tryit/domain/order/service/OrderDetailService.java
src/main/java/shop/tryit/domain/order/service/OrderFacade.java

- 주문 퍼사드에 주문 상세 조회 기능 구현
- 상품 엔티티에 메인 이미지 조회 기능 구현
- 주문 상세 엔티티에 메인 이미지 조회 기능 구현
- 주문 퍼사드에 주문 상세 조회 기능 구현

feat: 주문 퍼사드에 주문 상세 조회 기능 구현

---

src/main/resources/templates/payment/payment-form.html

- 주문 컨트롤러로 데이터 보낸 후 받는 상태코드 변경
- 200 -> 201 코드로 변경
- 201 코드를 받은 후 페이지 이동 href 변경

refactor: 주문 컨트롤러로 데이터 보낸 후 받는 상태코드 변경

---

src/main/resources/templates/carts/list.html

- 장바구니에서 선택된 상품 없이 주문 요청 시 "선택된 상품이 없습니다."라는 메세지의 alert을 추가

refactor: 장바구니에서 선택된 상품 없이 주문 요청 시 null 이슈 해결

---

src/main/java/shop/tryit/web/order/OrderController.java
src/main/resources/templates/orders/detail.html
src/main/resources/templates/orders/list.html

feat: 주문 컨트롤러에서 주문 상세 뷰 기능 구현

---

src/main/java/shop/tryit/domain/payment/PaymentFacade.java
src/main/java/shop/tryit/web/payment/PaymentController.java

- 결제 컨트롤러 검증 추가
- 장바구니 주문 시 각 상품의 주문 수량이 재고 보다 많을 때의 검증 처리를 하였습니다.
- 컨트롤러에서 검증 처리를 하게 될 시 특정 상품의 수량이  넘었는지 체크하기 어려워지는 문제가 발생하여 장바구니 js 에서 비동기로 처리하기로 결정.
- 비동기로 처리 후에도 문제가 생길 수 있다는 것을 고려하여 해당 검증 코드는 우선 남겨두기로 하고 후에 필요 없다 판단 시 삭제 할 예정

feat: 결제 컨트롤러 검증 추가

---

src/main/java/shop/tryit/domain/order/dto/OrderDetailDto.java
src/main/java/shop/tryit/domain/order/service/OrderFacade.java
src/main/java/shop/tryit/web/order/OrderController.java

- 주문 컨트롤러에 주문 등록 기능 구현
- 주문 컨트롤러에 주문 등록 기능 구현
- 주문 상세 dto의 인스턴스 변수명 수정
- 주문 취소 기능 삭제

feat: 주문 컨트롤러에 주문 등록 기능 구현

---

src/main/java/shop/tryit/domain/cart/repository/CartItemRepository.java
src/main/java/shop/tryit/domain/cart/service/CartItemService.java
src/main/java/shop/tryit/domain/order/service/OrderFacade.java
src/main/java/shop/tryit/repository/cart/CartItemJpaRepository.java
src/main/java/shop/tryit/repository/cart/CartItemRepositoryImpl.java

- 주문 등록시 장바구니 상품 삭제 기능 구현
- 주문할 때 장바구니에 해당 상품이 있을 경우에만 장바구니 상품이 제거되도록 기능 수정
- 주문할 때 장바구니에 없는 상품일 경우 장바구니는 그대로 유지

refactor: 주문 등록시 장바구니 상품 삭제 기능 구현

---

src/main/java/shop/tryit/domain/cart/repository/CartItemRepository.java
src/main/java/shop/tryit/domain/cart/service/CartItemService.java
src/main/java/shop/tryit/domain/order/service/OrderFacade.java
src/main/java/shop/tryit/repository/cart/CartItemJpaRepository.java
src/main/java/shop/tryit/repository/cart/CartItemRepositoryImpl.java

refactor: 장바구니에서 상품 삭제 버튼 기능 에러 수정

---

src/main/java/shop/tryit/domain/cart/repository/CartItemRepository.java
src/main/java/shop/tryit/domain/cart/service/CartItemService.java
src/main/java/shop/tryit/repository/cart/CartItemJpaRepository.java
src/main/java/shop/tryit/repository/cart/CartItemRepositoryImpl.java

- NPE 에러 방지를 위해 장바구니 상품 레포지토리에 findByCartAndItem 반환 값을 Optional로 변경

refactor: 장바구니 상품 레포지토리에 findByCartAndItem 반환 값을 Optional로 변경

---

src/main/java/shop/tryit/domain/cart/service/CartItemService.java
src/main/java/shop/tryit/domain/order/service/OrderFacade.java

refactor: 주문 등록시 장바구니 상품 삭제 기능 수정

---

src/main/java/shop/tryit/web/item/ItemController.java
src/main/resources/static/css/item.css
src/main/resources/templates/items/list.html

- 상품 목록 페이지 디자인 변경
- 상품 목록 html 구성 변경
- 상품 목록 관련 css 추가
- 한 페이지당 상품을 12개씩 보여주도록 변경

refactor: 상품 목록 페이지 디자인 변경

---

src/main/java/shop/tryit/domain/member/Member.java
src/main/java/shop/tryit/domain/order/OrderDetail.java
src/main/java/shop/tryit/domain/order/OrderDetailRepository.java
src/main/java/shop/tryit/domain/order/OrderRepository.java
src/main/java/shop/tryit/domain/order/dto/OrderDto.java
src/main/java/shop/tryit/domain/order/dto/OrderFindDto.java
src/main/java/shop/tryit/domain/order/dto/OrderSearchDto.java
src/main/java/shop/tryit/domain/order/entity/Order.java
src/main/java/shop/tryit/domain/order/entity/OrderDetail.java
src/main/java/shop/tryit/domain/order/entity/OrderStatus.java
src/main/java/shop/tryit/domain/order/service/OrderDetailService.java
src/main/java/shop/tryit/domain/order/service/OrderFacade.java
src/main/java/shop/tryit/domain/order/service/OrderService.java
src/main/java/shop/tryit/repository/order/OrderCustomImpl.java
src/main/java/shop/tryit/repository/order/OrderDetailCustom.java
src/main/java/shop/tryit/repository/order/OrderDetailCustomImpl.java
src/main/java/shop/tryit/repository/order/OrderDetailJpaRepository.java
src/main/java/shop/tryit/repository/order/OrderDetailRepositoryImpl.java
src/main/java/shop/tryit/repository/order/OrderJpaRepository.java
src/main/java/shop/tryit/repository/order/OrderRepositoryImpl.java
src/test/java/shop/tryit/domain/item/ItemRepositoryTests.java

- 주문 엔티티 패키지 변경
- 주문 엔티티 패키지 변경
- 주문 상세 엔티티 패키지 변경
- 주문 상태 패키지 변경

refactor: 주문 엔티티 패키지 변경

---

src/main/java/shop/tryit/domain/notice/service/NoticeFacade.java
src/main/java/shop/tryit/domain/notice/service/NoticeService.java

- 공지 수정, 삭제 안되는 이슈 해결
- 공지 서비스에 트랜잭션 제거
- 공지 퍼사드에 트랜잭션 추가

refactor: 공지 수정, 삭제 안되는 이슈 해결

---

src/main/java/shop/tryit/domain/qna/entity/Answer.java
src/main/java/shop/tryit/domain/qna/entity/Question.java
src/main/java/shop/tryit/domain/qna/service/QnAFacade.java
src/main/java/shop/tryit/web/qna/AnswerController.java
src/main/java/shop/tryit/web/qna/QuestionController.java
src/main/resources/templates/qna/answer-update.html
src/main/resources/templates/qna/detail-view.html

feat: 질문 삭제하기 및 댓글 수정하기 기능 추가

---

src/main/java/shop/tryit/domain/cart/service/CartFacade.java
src/main/java/shop/tryit/domain/item/entity/Item.java
src/main/java/shop/tryit/domain/item/service/ImageService.java
src/main/java/shop/tryit/domain/item/service/ImageStore.java
src/main/java/shop/tryit/domain/item/service/ItemFacade.java
src/main/java/shop/tryit/domain/item/service/ItemService.java
src/main/java/shop/tryit/domain/order/service/OrderFacade.java
src/main/java/shop/tryit/domain/payment/service/PaymentFacade.java
src/main/java/shop/tryit/web/item/ItemController.java

- 상품 도메인 관련 리팩토링
- 퍼사드 클래스 도입 전 ImageService에서 하나의 트랜잭션 안에서 작업하기 위해 상품 엔티티를 조회해오는 코드를 제거하기 위한 전반적으로 리팩토링을 진행

refactor: 상품 도메인 관련 리팩토링

---

src/main/java/shop/tryit/config/WebSecurityConfig.java
src/main/java/shop/tryit/domain/member/InitDB.java
src/main/java/shop/tryit/domain/member/entity/MemberRole.java
src/main/java/shop/tryit/domain/member/service/MemberFacade.java
src/main/java/shop/tryit/domain/member/service/MemberSecurityService.java
src/main/java/shop/tryit/domain/qna/service/QnAFacade.java
src/main/java/shop/tryit/web/qna/QuestionController.java

- 시큐리티 경로 보안 설정
- 기능 개발이 진행되는 동안 열어놓았던 시큐리티 경로 보안을 다시 설정하였습니다.
- 회원 권한에 "ROLE_" 이 붙은 것이 규칙이라 하여 적용 시켜 놓았으나 스프링부트 시큐리티에서 자동으로 설정해주는 것을 알게되어 MemberRole 의 Enum값을 변경하였습니다.

refactor: 시큐리티 경로 보안 설정

---

src/main/java/shop/tryit/config/WebSecurityConfig.java

- 리다이렉트 이슈 발견으로 관리자 권한 보안경로 수정

refactor: 리다이렉트 이슈로 인한 관리자 보안 경로 수정

---

src/main/java/shop/tryit/web/member/MemberController.java
src/main/resources/templates/fragments/body-header.html
src/main/resources/templates/members/update.html

- 회원 수정 관련 명칭 변경
- 통일성을 위해 edit -> update 로 명칭을 변경
- 네비게이션 바에서 회원 수정으로 가능 URL 변경
- 회원 수정 관련 URL 주소 변경

refactor: 회원 수정 관련 명칭 변경

---

src/main/resources/templates/members/login-form.html
src/main/resources/templates/members/register.html

- 회원 관련 웹 리팩토링
- 로그인 타이틀 한글로 수정
- 로그인 주석 수정 및 포맷팅
- 회원 가입 주석 수정 및 포맷팅

refactor: 회원 관련 웹 리팩토링

---

src/main/resources/static/css/notice.css
src/main/resources/templates/fragments/header.html
src/main/resources/templates/notices/detail.html
src/main/resources/templates/notices/list.html
src/main/resources/templates/notices/register.html
src/main/resources/templates/notices/update.html

feat: 공지에 css 적용

---

src/main/resources/static/css/qna.css
src/main/resources/templates/fragments/header.html
src/main/resources/templates/qna/answer-update.html
src/main/resources/templates/qna/check-password.html
src/main/resources/templates/qna/detail-view.html
src/main/resources/templates/qna/list.html
src/main/resources/templates/qna/register.html
src/main/resources/templates/qna/update.html

feat: 질문 게시판 페이지 디자인 변경

---

src/main/resources/static/css/style.css
src/main/resources/templates/payment/payment-form.html

- 결제 폼에 적용된 css 변경 및 포맷팅
- 결제 폼에 적용된 hero css 에서 common css로 변경
- 주석 수정 및 삭제 포맷팅
- 확인을 위한 consol.log() 로직 삭제

refactor: 결제 폼에 적용된 css 변경 및 포맷팅

---

src/main/java/shop/tryit/domain/order/dto/OrderFindDto.java
src/main/java/shop/tryit/domain/order/entity/Order.java
src/main/java/shop/tryit/domain/order/entity/OrderDetail.java
src/main/java/shop/tryit/domain/order/service/OrderFacade.java
src/main/java/shop/tryit/web/order/OrderController.java
src/main/resources/static/css/order.css
src/main/resources/templates/fragments/header.html
src/main/resources/templates/orders/detail.html
src/main/resources/templates/orders/list.html

- 주문 페이지에 디자인 적용하기
- 주문 페이지에 디자인 적용하기
- 주문 dto에 회원 정보, 주소 정보 추가

feat: 주문 페이지에 디자인 적용하기

---

src/main/resources/static/css/cart.css
src/main/resources/static/css/common.css
src/main/resources/static/css/item.css
src/main/resources/templates/items/detail.html
src/main/resources/templates/items/register.html
src/main/resources/templates/items/update.html

- 상품 등록, 수정, 상세 페이지 디자인 변경
- 추후 기재

refactor: 상품 페이지 디자인 변경

---

build.gradle
src/main/resources/application.yml

build: db 변경

---

src/main/java/shop/tryit/web/notice/NoticeController.java

feat: 공지사항 수정 시 검증 기능 추가

---

src/main/java/shop/tryit/web/qna/AnswerController.java
src/main/resources/static/css/qna.css
src/main/resources/templates/qna/answer-update.html
src/main/resources/templates/qna/detail-view.html

feat: 댓글 기능 버튼을 관리자만 보이도록 설정

---

src/main/java/shop/tryit/config/WebSecurityConfig.java

- 회원권한과 어드민권한에서 동작해야하는 경로가 시큐리티 문제로 되지 않는 문제가 발생하여 이를 수정하였습니다.

refactor: 시큐리티 보안 경로 수정

---

src/main/java/shop/tryit/config/WebSecurityConfig.java
src/main/java/shop/tryit/domain/cart/service/CartFacade.java
src/main/java/shop/tryit/domain/member/service/MemberSecurityService.java

- 시큐리티 config 수정 및 장바구니 퍼사드 @Transactional 추가

refactor: 시큐리티 config 수정 및 장바구니 퍼사드 @Transactional 추가

---

src/main/java/shop/tryit/domain/notice/service/NoticeService.java
src/main/java/shop/tryit/domain/qna/service/AnswerService.java
src/main/java/shop/tryit/web/qna/QuestionController.java

refactor: QnA / 공지 페이징 사이즈 개수 변경

---

src/main/java/shop/tryit/domain/qna/service/QnAFacade.java
src/main/java/shop/tryit/web/qna/QuestionController.java
src/main/resources/templates/qna/detail-view.html

- 게시글 기능 관련 버튼을 작성자 또는 관리자한테만 보이도록 설정

feat: 게시글 기능 관련 버튼을 작성자 또는 관리자한테만 보이도록 설정

---

build.gradle
src/main/java/shop/tryit/TryitApplication.java
src/main/java/shop/tryit/domain/item/dto/ItemResponseDto.java
src/main/java/shop/tryit/domain/item/dto/ItemSearchDto.java
src/main/java/shop/tryit/domain/item/service/ImageService.java
src/main/java/shop/tryit/domain/item/service/ImageStore.java
src/main/java/shop/tryit/domain/item/service/ItemFacade.java
src/main/java/shop/tryit/domain/item/service/S3Service.java
src/main/java/shop/tryit/repository/item/ItemCustomImpl.java
src/main/java/shop/tryit/web/item/ImageController.java
src/main/resources/application.yml
src/main/resources/templates/items/detail.html
src/main/resources/templates/items/list.html

- 이미지 파일이 로컬 서버가 아닌 aws s3에 업로드 되도록 변경

refactor: aws s3 적용

---

src/main/java/shop/tryit/domain/cart/dto/CartListDto.java
src/main/java/shop/tryit/domain/cart/service/CartFacade.java
src/main/java/shop/tryit/domain/order/dto/OrderFindDto.java
src/main/java/shop/tryit/domain/order/service/OrderFacade.java
src/main/java/shop/tryit/domain/payment/dto/PaymentResponseDto.java
src/main/java/shop/tryit/domain/payment/service/PaymentFacade.java
src/main/resources/templates/carts/list.html
src/main/resources/templates/orders/detail.html
src/main/resources/templates/payment/payment-form.html

refactor: 주문, 장바구니, 결제 뷰에서 s3로 이미지 조회

---

src/main/java/shop/tryit/domain/item/dto/ItemResponseDto.java
src/main/java/shop/tryit/domain/item/service/ImageService.java
src/main/java/shop/tryit/domain/item/service/ImageStore.java
src/main/java/shop/tryit/domain/item/service/ItemFacade.java
src/main/resources/templates/items/detail.html

- 상품 삭제 시 aws s3에 저장된 이미지가 삭제되도록 함.
- 상품 수정 시 aws s3에는 변경 기능이 없기 때문에 저장된 기존 이미지를 삭제하고 새로운 이미지를 새로 저장하도록 함.

refactor: aws s3 삭제 및 수정 적용

---

.gitignore
src/main/resources/application-security.yml
src/main/resources/application.yml

- 보안에 민감한 정보가 담긴 yml 파일을 따로 분리하여 gitignore에 적용

Build: yml 파일 gitignore 적용

---

src/main/resources/static/css/item.css
src/main/resources/templates/items/detail.html

- 상품 상세 페이지에서 상품 이미지가 텍스트 쪽으로 벗어나 이미지 크기를 조절

refactor: 상품 상세 뷰에 상품 이미지 크기 조절 

---

src/main/resources/templates/notices/detail.html
src/main/resources/templates/notices/register.html
src/main/resources/templates/notices/update.html

- 공지사항에 관리자만 공지 관련 기능 버튼이 보이도록 설정

feat: 공지사항에 관리자만 공지 관련 기능 버튼이 보이도록 설정

---

src/main/java/shop/tryit/web/qna/QuestionController.java
src/main/resources/static/css/qna.css
src/main/resources/templates/qna/answer-update.html
src/main/resources/templates/qna/check-password.html

- QnA 비밀번호 체크 폼의 디자인 변경 및 검증 메세지가 나오지 않는 이슈 해결
- QnA 비밀번호 체크 폼의 검증 메시지가 보이도록 수정
- QnA 비밀번호 체크 폼의 css 수정

refactor: QnA 비밀번호 체크 폼의 디자인 변경 및 검증 메세지가 나오지 않는 이슈 해결

---

src/main/java/shop/tryit/domain/item/service/ImageStore.java

- 지정된 경로가 없을 시 해당 경로 생성 기능 추가
- 파일 업로드시 지정된 경로에 폴더가 없을 경우 에러가 발생하는 이슈 발생.
- 해결 방안: 지정된 경로에 폴더가 없을 경우 폴더를 생성해주는 로직 추가

refactor: 지정된 경로가 없을 시 해당 경로 생성 기능 추가

---

src/main/java/shop/tryit/web/cart/CartController.java
src/main/java/shop/tryit/web/item/ItemController.java
src/main/java/shop/tryit/web/member/MemberController.java
src/main/java/shop/tryit/web/order/OrderController.java
src/main/java/shop/tryit/web/payment/PaymentController.java
src/main/java/shop/tryit/web/qna/AnswerController.java
src/test/java/shop/tryit/domain/item/ItemServiceTests.java

- thymeleaf 이슈(Error resolving template) 해결
- AWS는 리눅스 환경으로 돌아가기 때문에 로컬서버(내부 톰캣)과의 경로 차이가 있다는 것을 알게 되어 전반적인 Controller 리팩토링을 진행
- 전반적인 Controller return 경로를 수정

refactor: thymeleaf 이슈(Error resolving template) 해결

---

src/main/java/shop/tryit/web/order/OrderController.java

refactor: 주문 등록시 location url 주소 수정

---

src/main/java/shop/tryit/domain/qna/service/QnAFacade.java

refactor: QnA에서 질문 게시글의 페이징 사이즈 수정
