- src/main/java/shop/tryit/domain/item/Item.java
- src/main/java/shop/tryit/domain/item/ItemFile.java
- src/main/java/shop/tryit/domain/item/ItemFileStore.java
- src/main/resources/application.yml
- 상품 이미지 파일 업로드 기능 구현
- 클라이언트 ➡ 상품 메인 이미지 1장, 상품 상세 이미지 여러장 업로드 가능
- 서버 ➡ 업로드된 파일명을 uuid를 사용해 중복이 없도록 변환해서 저장
- 파일 업로드 경로는 추후 변경이 필요
> feat: 상품 이미지 파일 업로드 기능 구현

- src/main/java/shop/tryit/domain/item/Category.java
- src/main/java/shop/tryit/domain/item/Item.java
- src/main/java/shop/tryit/web/item/ItemController.java
- src/main/resources/templates/items/register.html
- 카테고리를 엔티티에서 enum으로 변경
- Category를 엔티티에서 enum 타입으로 변경
- 상품과 카테고리간 연관관계 매핑 제거 ➡ Enumerated로 수정
- 상품 컨트롤러에서 카테고리 리스트를 뷰로 넘겨주는 과정 추가
- 뷰(register.html)에서 카테고리를 뿌려주는 방법을 radio에서 select 형식으로 변경
> refactor: 상품 카테고리 enum 타입으로 변경

- src/main/java/shop/tryit/domain/item/Item.java
- src/main/java/shop/tryit/domain/item/ItemFile.java
- src/main/java/shop/tryit/domain/item/ItemFileStore.java
- src/main/java/shop/tryit/domain/item/ItemFileType.java
- src/main/java/shop/tryit/web/item/ItemAdapter.java
- src/main/java/shop/tryit/web/item/ItemController.java
- src/main/java/shop/tryit/web/item/ItemFormDto.java
- src/main/resources/templates/items/register.html
- 상품 이미지 파일(ItemFile) 엔티티 구조 변경에 따른 리팩토링
- 상품(Item) 엔티티의 메인이미지, 상세 이미지 필드를 상품 이미지라는 하나의 필드로 관리하도록 변경
- 상품 파일(ItemFile) 엔티티에 type 필드를 추가해 enum 타입(MAIN, DETAIL)으로 해당 이미지 파일의 용도를 명시
- 사용자는 상세 이미지 파일을 1개만 업로드 가능하도록 변경
- 컨트롤러에 있던 DTO->엔티티 로직을 ItemAdapter로 분리
> refactor: 상품 파일 엔티티 구조 변경 

- src/main/java/shop/tryit/domain/item/Image.java
- src/main/java/shop/tryit/domain/item/ImageService.java
- src/main/java/shop/tryit/domain/item/ImageStore.java
- src/main/java/shop/tryit/domain/item/ItemService.java
- src/main/java/shop/tryit/web/item/ItemAdapter.java
- src/main/java/shop/tryit/web/item/ItemController.java
- src/main/java/shop/tryit/web/item/ItemUpdateDto.java
- src/main/resources/templates/items/update.html
- 상품 수정 관련 개발
- domain
- 기존 서버에 저장되어 있던 이미지 파일을 삭제하는 로직 추가
- DB에 보관되는 상품 이미지 정보 수정을 위해 상품 엔티티에 `update` 기능 추가
- 상품 이미지 서비스 (ImageService)
- 상품의 메인, 상세 이미지를 수정하는 서비스 로직 추가
- 상품의 메인, 상세 이미지를 조회해오는 서비스 로직 추가
- web
- 상품 수정용 DTO 생성 (ItemUpdateDto)
- `상품 엔티티` ➡ `상품 수정 DTO`로 변환해주는 어댑터 기능 추가
- 상품 수정 뷰 생성
- 상품 수정 관련 컨트롤러 구현
>  feat: 상품 수정 개발

- src/main/java/shop/tryit/domain/item/Item.java
- src/main/java/shop/tryit/domain/item/NotEnoughStockException.java
- src/main/java/shop/tryit/domain/order/Order.java
- src/main/java/shop/tryit/domain/order/OrderDetail.java
- src/main/java/shop/tryit/domain/order/OrderService.java
- src/test/java/shop/tryit/domain/order/OrderServiceTests.java
- 단건 주문 관련하여 서비스를 구현 하였습니다.
- 상품 엔티티에 재고 관리 메소드 추가
- 상품 재고 관리 시 발생 할 수 있는 에러 클래스 생성
- 주문 관련 엔티티에 주문 취소 관련 메소드 생성
- 주문 서비스 생성 
- 주문 서비스 테스트 생성
> feat: 주문 관련 서비스 구현(단건 주문 서비스)

- src/main/java/shop/tryit/domain/item/Image.java
- src/main/java/shop/tryit/domain/item/ItemRepository.java
- src/main/java/shop/tryit/domain/item/ItemSearchCondition.java
- src/main/java/shop/tryit/domain/item/ItemService.java
- src/main/java/shop/tryit/repository/item/ItemCustom.java
- src/main/java/shop/tryit/repository/item/ItemCustomImpl.java
- src/main/java/shop/tryit/repository/item/ItemJpaRepository.java
- src/main/java/shop/tryit/repository/item/ItemRepositoryImpl.java
- src/main/java/shop/tryit/web/item/ItemAdapter.java
- src/main/java/shop/tryit/web/item/ItemController.java
- src/main/java/shop/tryit/web/item/ItemSearchDto.java
- src/test/java/shop/tryit/domain/item/ItemServiceTests.java
- 상품 목록 검색, 페이징 처리
- 상품 검색 조건 생성 (상품 이름, 상품 카테고리)
- 검색을 위한 상품 커스텀 레포지토리 인터페이스와 구현체 생성
- 상품 레포지토리에 상품 검색 기능 추가
- 상품 서비스 구현과 테스트 진행
- 리팩토링
- 상품 목록 DTO 클래스명 변경 `ItemListDto` -> `ItemSearchDto`
- 상품 검색 메소드명 변경 `searchItem` -> `searchItems`
>  feat: 상품 목록 검색, 페이징 처리

- src/main/java/shop/tryit/repository/item/ItemCustomImpl.java
- QItemListDTO -> QItemSearchDto 로 클래스명 변경
- ItemCustomlmpl 에서 리팩토링 된 클래스의 Q클래스가 같이 리팩토링 되지 않아 발생한 이슈인 듯 합니다.
- 해서 리팩토링된 클래스의 이름으로 Q클래스를 변경하여 문제를 해결 하였습니다.
> refactor: QItemListDTO -> QItemSearchDto 로 클래스명 변경

- src/main/resources/templates/items/detail.html
- src/main/resources/templates/items/list.html
- 사용자 권한에 따른 상품 뷰 처리
- 상품 상세 폼에서 상품 수정, 삭제 버튼 관리자 계정에서만 보이도록 처리
- 상품 목록 폼에서 상품 등록 버튼 관리자 계정에서만 보이도록 처리
> feat: 사용자 권한에 따른 상품 뷰 처리

- src/main/java/shop/tryit/web/item/ItemController.java
- src/main/java/shop/tryit/web/order/OrderController.java
- src/main/java/shop/tryit/web/order/OrderFormDto.java
- src/main/resources/static/css/style.css
- src/main/resources/templates/items/detail.html
- 상품 상세 폼에서 단건 주문 처리
- 상품 상세 폼 css와 구성 변경
- 상품 상세 폼에서 주문 컨트롤러로 값을 넘겨주기 위해 상품 상세 컨트롤러에서 빈 `OrderFormDto` 객체를 모델에 담아 넘겨줌
- 상품 상세 폼에서 `상품 ID`와 `수량` 값을 주문 컨트롤러로 전달하도록 함
- 주문 컨트롤러에서 DTO로 값을 받을 때 `itemName`과 `itemPrice`는 DB에서 조회해온 값으로 주입해주도록 함
> feat: 상품 상세 폼에서 단건 주문 처리

- src/main/java/shop/tryit/domain/question/QuestionSearchCondition.java
- src/main/java/shop/tryit/repository/question/QuestionCustomImpl.java
- src/main/resources/templates/questions/list.html
- 질문 검색 기준을 1개로 통합
- 질문 검색 기준인 `제목`, `이메일` 을 1개로 통합
> refactor: 질문 검색 기준을 1개로 통합

- src/main/java/shop/tryit/domain/cart/repository/CartRepository.java
- src/main/java/shop/tryit/domain/cart/service/CartService.java
- src/main/java/shop/tryit/repository/cart/CartJpaRepository.java
- src/main/java/shop/tryit/repository/cart/CartRepositoryImpl.java
- src/test/java/shop/tryit/domain/cart/CartServiceTests.java
- 회원 별로 하나의 장바구니를 생성하는 기능 개발
- 장바구니 레포지토리에 `findByMember()` 추가
- 장바구니 생성 비즈니스 로직 구현
- 해당 회원에게 장바구니가 없을 경우에만 장바구니를 생성하도록 구현
- 장바구니 생성 비즈니스 로직 테스트 코드
> feat: 장바구니 생성 서비스 로직 개발

- src/main/java/shop/tryit/domain/cart/entity/CartItem.java
- src/main/java/shop/tryit/domain/cart/repository/CartItemRepository.java
- src/main/java/shop/tryit/domain/cart/service/CartItemService.java
- src/main/java/shop/tryit/repository/cart/CartItemJpaRepository.java
- src/main/java/shop/tryit/repository/cart/CartItemRepositoryImpl.java
- src/test/java/shop/tryit/domain/cart/CartItemServiceTests.java
- 장바구니에 상품을 추가하는 기능 개발
- 장바구니 상품 레포지토리에 `findByCartAndItem()` 추가
- 장바구니 상품 엔티티에 `addCount()` 추가
- 장바구니 상품 추가 비즈니스 로직 수정
- 장바구니에 같은 상품을 담을 경우 개수가 증가하도록 구현
- 장바구니에 새로운 상품을 담을 경우 장바구니 상품을 추가하도록 구현 
- 장바구니 상품 추가 비즈니스 로직 테스트 코드
> feat: 장바구니 상품 추가 서비스 로직 개발

- src/main/java/shop/tryit/domain/cart/entity/CartItem.java
- src/main/java/shop/tryit/domain/cart/repository/CartItemRepository.java
- src/main/java/shop/tryit/domain/cart/service/CartItemService.java
- src/main/java/shop/tryit/repository/cart/CartItemRepositoryImpl.java
- src/test/java/shop/tryit/domain/cart/CartItemServiceTests.java
- 장바구니 상품의 수량을 변경하는 기능을 개발
- 장바구니 상품 레포지토리에 `findById()` 추가
- 장바구니 상품 엔티티에 `updateCount()` 추가
- 장바구니에 담긴 상품의 수량을 변경하는 서비스 로직 구현 : `updateCartItemCount()`
- 장바구니에 담긴 상품의 수량을 변경하는 서비스 로직 테스트 코드
- 주석 메세지 수정
> feat: 장바구니 상품 수정 기능 개발

- src/main/java/shop/tryit/domain/cart/repository/CartItemRepository.java
- src/main/java/shop/tryit/domain/cart/service/CartItemService.java
- src/main/java/shop/tryit/repository/cart/CartItemRepositoryImpl.java
- src/test/java/shop/tryit/domain/cart/CartItemServiceTests.java
- 장바구니에 담긴 상품을 삭제하는 기능 개발
- 장바구니 상품 레포지토리에 `delete()` 추가
- 장바구니에 담긴 상품을 삭제하는 비즈니스 로직 구현 : `deleteCartItem`
- 장바구니에 담긴 상품을 삭제하는 비즈니스 로직 테스트 코드
- 장바구니 상품의 주문이 일어나 장바구니에서 삭제되는 경우는 추후에 주문과 맞춰서 진행하도록 한다.
> feat: 장바구니 상품 삭제 기능 개발

- src/main/java/shop/tryit/web/item/ItemController.java
- src/main/java/shop/tryit/web/payment/PaymentController.java
- src/main/java/shop/tryit/web/payment/PaymentFormDto.java
- src/main/resources/templates/items/detail.html
- 결제 기능 추가로 인해 상품 상세에서 단건 주문 시 결제 컨트롤러로 정보 전달하도록 함.
- 상품 상세 폼에서 주문하기 버튼을 눌렀을 때 주문 컨트롤러가 아닌 결제 컨트롤러로 전달되도록 변경
- 결제 컨트롤러에서 정보를 받기 위한 결제 폼 DTO 생성 : `PaymentFormDto`
- 정보가 잘 넘어가는지 확인을 위해 결제 폼 생성 컨트롤러에 `@ModelAttribute` 추가
- style 수정
- 클래스명 : `PayController` -> `PaymentController`
- 메소드명 : `newKakapay` -> `newPaymentForm` (새로운 결제폼 생성의 의미)
- @Kimjunghyunn 
- 결제할 상품의 정보 전달 여부 확인만 해놓은 상태라서 전달받은 정보를 Model에 담아 View로 전달하는 로직을 추가해주면 될 것 같아요.😊
> feat: 상품 상세에서 단건 주문 시 결제 컨트롤러로 정보 전달

- src/main/java/shop/tryit/domain/cart/entity/CartItem.java
- src/main/java/shop/tryit/domain/cart/service/CartItemService.java
- src/main/java/shop/tryit/domain/cart/service/CartService.java
- src/main/java/shop/tryit/web/cart/controller/CartController.java
- src/main/java/shop/tryit/web/cart/dto/CartItemAdapter.java
- src/main/java/shop/tryit/web/cart/dto/CartItemDto.java
- src/main/resources/templates/items/detail.html
- src/test/java/shop/tryit/domain/cart/CartItemServiceTests.java
- src/test/java/shop/tryit/domain/cart/CartServiceTests.java
- 장바구니 웹 계층 개발 (상품 담기)
- 장바구니 상품 Dto 생성
- 장바구니 상품 Dto ➡ Entity 변환 어댑터 생성
- 상품 상세 폼에서 장바구니 담기 버튼을 클릭 시 데이터를 전달하는 자바스크립트 코드 추가
- 리팩토링
- 장바구니 생성 서비스 로직 반환 타입 변경 및 테스트 코드 수정  
- 장바구니 상품 Entity 수량 필드명을 `count` ➡ `quantity`로 변경
- 장바구니 서비스 로직 메소드명을 `createCart` ➡ `findCart`로 변경
> feat: 장바구니 웹 계층 개발 (상품 담기)

- src/main/java/shop/tryit/domain/cart/entity/CartItem.java
- src/main/java/shop/tryit/web/cart/controller/CartController.java
- src/main/java/shop/tryit/web/cart/dto/CartItemAdapter.java
- src/main/java/shop/tryit/web/cart/dto/CartListDto.java
- src/main/resources/static/css/style.css
- src/main/resources/templates/cart/list.html
- 장바구니 웹 계층 개발 (조회)
- 장바구니 목록 Dto 생성 : `itemListDto`
- 장바구니 목록 Dto ➡ Entity 변환 어댑터 생성
- 장바구니에 담긴 상품 목록을 조회하는 컨트롤러 추가
- 장바구니 목록 뷰 생성 : `cart/list.html`
- css 코드 추가
- 리팩토링
- 장바구니 상품 엔티티에 `getItemId()`, `getItemName()`, `getItemPrice()` 추가
- 디미터 법칙을 준수하도록 컨트롤러, 어댑터 코드 리팩토링
- 현재 proxy 객체로 조회되어 발생되는 이슈 해결 필요
> feat: 장바구니 웹 계층 개발 (조회)

- src/main/java/shop/tryit/web/cart/controller/CartController.java
- src/main/resources/templates/fragments/body-header.html
- src/main/resources/templates/items/detail.html
- 장바구니 URI를 `/cart`에서 `/carts`로 변경
- 컨트롤러 매핑 경로 변경
- 상단 네비게이션바 장바구니 링크 변경
> refactor: 장바구니 URI 변경

- src/main/java/shop/tryit/domain/cart/entity/CartItem.java
- src/main/java/shop/tryit/domain/cart/service/CartFacade.java
- src/main/java/shop/tryit/domain/cart/service/CartItemService.java
- src/main/java/shop/tryit/domain/item/entity/Item.java
- src/main/java/shop/tryit/web/cart/CartController.java
- 장바구니 관련 리팩토링
- 장바구니 컨트롤러에서 장바구니 상품 담기 검증에 사용되는 로직을 비즈니스 로직으로 분리
- `Facade`에서 dto<-entity 변환 기능으로 사용되는 메소드의 접근지시자를 `private`으로 수정
- 동일 상품을 장바구니에 담을 때 장바구니 수량 증가가 일어나지 않는 이슈
- `Facade`에 적용되어 있는 트랜잭션이 `Service`까지 영향을 주는 것으로 확인
- `Service`에 적용되는 트랜잭션을 모두 지우고, `Facade`에서만 적용되도록 수정
> refactor: 장바구니 관련 리팩토링

- src/main/java/shop/tryit/domain/cart/dto/CartListDto.java
- src/main/java/shop/tryit/domain/cart/service/CartFacade.java
- src/main/java/shop/tryit/domain/cart/service/CartItemService.java
- src/main/java/shop/tryit/web/cart/CartController.java
- src/main/resources/templates/carts/list.html
- src/test/java/shop/tryit/domain/cart/CartItemServiceTests.java
- 장바구니 목록에서 수량 변경 처리
- CartListDto에 cartItemId 멤버변수 추가
- CartFacade에 장바구니 상품 수량을 변경하는 기능 추가
- 장바구니 폼에서 수량 버튼 조작 시 장바구니 상품 수량 변경을 요청하는 js 추가
- 장바구니 상품 수량 변경 요청을 받는 컨트롤러 추가
- 처음에 체크박스가 모두 체크되어 있도록 checked 속성 추가
- 장바구니에서 수량 버튼 조작으로 DB에 데이터 변경이 일어난뒤, 상품 개별 합계와 결제 예정 금액 변경이 새로고침을 통해 일어나는데 이때 체크박스 체크 유무까지 같이 초기화 되기 때문에 추후 js 리팩토링이 필요
> feat: 장바구니 목록에서 수량 변경 처리

- src/main/java/shop/tryit/domain/cart/dto/CartListDto.java
- src/main/resources/templates/carts/list.html
- src/main/resources/templates/items/detail.html
- 장바구니 목록 폼 js 리팩토링
- 장바구니에서 수량 버튼 조작시 다음이 모두 발생하도록 변경
- 장바구니 상품 개별 합계 값 세팅
- 총 장바구니 정보(결제 예정 금액) 세팅
- 서버로 장바구니 상품 수량 변경 요청
- 기존에는 `CartListDto`에서 멤버변수에 `totalPrice`를 두고 서버쪽에서 계산하여 뷰에서 사용했는데, 뷰에서 계산하여 사용하도록 변경
> refactor: 장바구니 목록 폼 js 리팩토링

- src/main/java/shop/tryit/domain/cart/service/CartFacade.java
- src/main/java/shop/tryit/web/cart/CartController.java
- src/main/resources/templates/carts/list.html
- 장바구니 목록 페이지에서 삭제 버튼 클릭 시 장바구니에서 해당 상품이 삭제되도록 개발
- `CartFacade`에 장바구니 상품 삭제 기능 추가
- 장바구니 목록 폼에 서버로 장바구니 상품 삭제 요청을 보내는 js 추가
- 장바구니 상품 삭제 요청을 받는 컨트롤러 추가
> feat: 장바구니 목록에서 삭제 버튼 처리

- src/main/java/shop/tryit/domain/cart/dto/CartListDto.java
- src/main/java/shop/tryit/domain/cart/entity/CartItem.java
- src/main/java/shop/tryit/domain/cart/service/CartFacade.java
- src/main/resources/templates/carts/list.html
- 장바구니에서 상품의 재고보다 많은 수량을 주문할 수 없도록 프론트 측에서 검증을 진행
- `CartListDto`에 `itemStock` 멤버변수를 추가해 뷰에 전달
- `CartItem` 엔티티에 상품 재고를 반환하는 `getItemStock()` 추가
- 장바구니에서 주문하려는 수량만큼 상품의 재고가 충분한지 확인하는 조건문 추가
> refactor: 장바구니에서 상품의 재고보다 많은 수량을 주문할 수 없도록 검증 처리

- src/main/java/shop/tryit/web/qna/AnswerController.java
- src/main/java/shop/tryit/web/qna/QuestionController.java
- 게시판 수정, 댓글 삭제 기능 이슈 해결
- 게시판 수정, 댓글 삭제 기능 이슈 해결
- 댓글 삭제 및 조회 순서 변경 (조회 후 삭제)
- 관리자는 비밀번호 없이 들어갈 수 있도록 권한 설정
- 게시판 수정시 기존에 작성했던 글 불러오기 기능 추가
> refactor: 게시판 수정, 댓글 삭제 기능 이슈 해결

- src/main/java/shop/tryit/config/WebSecurityConfig.java
- ADMIN 권한일 경우 경로 보안 위치 변경
- antMatchers()의 위치에 따라 세부적으로 경로가 지정되는 것으로 보여짐
- 따라서 전체적인 권한을 가지고 있는 관리자 권한 위치를 맨 위로 올림
> refactor: ADMIN 권한일 경우 경로 보안 위치 변경

- src/main/java/shop/tryit/web/qna/QuestionController.java
- 본인 및 관리자 제외시 게시글 수정 막기 기능 추가
-  본인 및 관리자가 아닌 사람이 게시글 수정 버튼 클릭시 작동이 안되도록 구현
> refactor: 본인 및 관리자 제외시 게시글 수정 막기 기능 추가

- src/main/java/shop/tryit/web/qna/AnswerController.java
- 답변 검증 메시지가 뜰 때 기존 답변들이 안보였는데 보이도록 수정
> refactor: QnA 답글 등록 시 검증 메시지가 뜰 때 기존 답변들이 보이지 않는 이슈 해결
